using BrowserApi.Generator.Input;
using BrowserApi.Generator.Resolution;
using BrowserApi.Generator.Transform;
using BrowserApi.Generator.Emit;

namespace BrowserApi.Generator.Tests.EndToEnd;

public class ConsoleEmitTests {
    private static string SpecPath(string relativePath) {
        var dir = AppContext.BaseDirectory;
        while (dir != null && !File.Exists(Path.Combine(dir, "BrowserApi.sln")))
            dir = Path.GetDirectoryName(dir);
        return Path.Combine(dir!, relativePath);
    }

    [Fact]
    public void Console_spec_produces_valid_class() {
        // Parse
        var reader = new WebRefJsonReader();
        var spec = reader.ReadSpec(SpecPath("specs/idlparsed/console.json"));

        // Resolve
        var resolver = new IdlResolver();
        var model = resolver.Resolve([spec]);

        // Transform
        var transformer = new IdlToCSharpTransformer(model);
        var csModel = transformer.Transform(model);

        // Find the console class
        var consoleClass = csModel.Classes.FirstOrDefault(c => c.JsName == "console" || c.Name == "Console");
        Assert.NotNull(consoleClass);
        Assert.Equal("Console", consoleClass.Name);

        // Emit
        var output = ClassEmitter.Emit(consoleClass);

        Assert.Contains("// <auto-generated/>", output);
        Assert.Contains("public partial class Console", output);
        Assert.Contains("Log", output);
        Assert.Contains("Error", output);
        Assert.Contains("Warn", output);
        Assert.Contains("void", output);
    }

    [Fact]
    public void Fetch_spec_produces_enums_and_interfaces() {
        var reader = new WebRefJsonReader();
        var spec = reader.ReadSpec(SpecPath("specs/idlparsed/fetch.json"));

        var resolver = new IdlResolver();
        var model = resolver.Resolve([spec]);

        var transformer = new IdlToCSharpTransformer(model);
        var csModel = transformer.Transform(model);

        // Should have RequestDestination enum
        var destEnum = csModel.Enums.FirstOrDefault(e => e.Name == "RequestDestination");
        Assert.NotNull(destEnum);
        Assert.True(destEnum.Members.Count > 5);

        var output = EnumEmitter.Emit(destEnum);
        Assert.Contains("public enum RequestDestination", output);
        Assert.Contains("[StringValue(\"audio\")]", output);

        // Should have Request class with merged Body members
        var requestClass = csModel.Classes.FirstOrDefault(c => c.Name == "Request");
        Assert.NotNull(requestClass);
        // Should have Body members merged in (bodyUsed, text, etc.)
        Assert.Contains(requestClass.Properties, p => p.Name == "BodyUsed");
        Assert.Contains(requestClass.Methods, m => m.Name == "TextAsync");
    }
}
