using BrowserApi.Generator.Emit;
using BrowserApi.Generator.Input;
using BrowserApi.Generator.Resolution;
using BrowserApi.Generator.Transform;

namespace BrowserApi.Generator.Tests.EndToEnd;

public class FullPipelineTests {
    private static string SpecPath(string relativePath) {
        var dir = AppContext.BaseDirectory;
        while (dir != null && !File.Exists(Path.Combine(dir, "BrowserApi.sln")))
            dir = Path.GetDirectoryName(dir);
        return Path.Combine(dir!, relativePath);
    }

    [Fact]
    public void Fetch_spec_through_full_pipeline() {
        // Parse
        var reader = new WebRefJsonReader();
        var spec = reader.ReadSpec(SpecPath("specs/idlparsed/fetch.json"));

        // Resolve
        var resolver = new IdlResolver();
        var model = resolver.Resolve([spec]);

        // Transform
        var transformer = new IdlToCSharpTransformer(model);
        var csModel = transformer.Transform(model);

        // Verify Request class exists with Body mixin merged
        var requestClass = csModel.Classes.FirstOrDefault(c => c.Name == "Request");
        Assert.NotNull(requestClass);
        Assert.Contains(requestClass.Properties, p => p.Name == "Method");
        Assert.Contains(requestClass.Properties, p => p.Name == "Url");
        Assert.Contains(requestClass.Properties, p => p.Name == "BodyUsed"); // from Body mixin
        Assert.Contains(requestClass.Methods, m => m.Name == "TextAsync"); // from Body mixin
        Assert.Contains(requestClass.Methods, m => m.Name == "JsonAsync"); // from Body mixin

        // Verify enums
        Assert.Contains(csModel.Enums, e => e.Name == "RequestDestination");
        Assert.Contains(csModel.Enums, e => e.Name == "RequestMode");
        Assert.Contains(csModel.Enums, e => e.Name == "ResponseType");

        // Verify dictionaries
        Assert.Contains(csModel.RecordClasses, r => r.Name == "RequestInit");
        Assert.Contains(csModel.RecordClasses, r => r.Name == "ResponseInit");

        // Verify Body mixin is not a separate class (it should be removed after includes merge)
        Assert.DoesNotContain(csModel.Classes, c => c.Name == "Body");

        // Emit and verify no crashes
        var fileEmitter = new FileEmitter();
        var outputDir = Path.Combine(Path.GetTempPath(), "BrowserApi.Generator.Tests", Guid.NewGuid().ToString());
        try {
            var count = fileEmitter.EmitAll(csModel, outputDir);
            Assert.True(count > 0);

            // Verify files were written
            var files = Directory.GetFiles(outputDir, "*.g.cs", SearchOption.AllDirectories);
            Assert.True(files.Length > 0);

            // Spot-check Request.g.cs
            var requestFile = files.FirstOrDefault(f => Path.GetFileName(f) == "Request.g.cs");
            Assert.NotNull(requestFile);
            var content = File.ReadAllText(requestFile);
            Assert.Contains("public partial class Request", content);
            Assert.Contains("// <auto-generated/>", content);
        } finally {
            if (Directory.Exists(outputDir))
                Directory.Delete(outputDir, recursive: true);
        }
    }

    [Fact]
    public void Multiple_specs_resolve_together() {
        var reader = new WebRefJsonReader();
        var specs = new[] {
            reader.ReadSpec(SpecPath("specs/idlparsed/dom.json")),
            reader.ReadSpec(SpecPath("specs/idlparsed/html.json")),
            reader.ReadSpec(SpecPath("specs/idlparsed/fetch.json")),
        };

        var resolver = new IdlResolver();
        var model = resolver.Resolve(specs);

        // Should have types from all specs
        Assert.True(model.Interfaces.Count > 20);
        Assert.True(model.Enums.Count > 3);

        var transformer = new IdlToCSharpTransformer(model);
        var csModel = transformer.Transform(model);

        // Should produce lots of classes
        Assert.True(csModel.Classes.Count > 20);
    }
}
