coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
        target: auto

ignore:
  - "src/BrowserApi/Generated/**"
  - "src/BrowserApi.Generator/**"
  - "tests/**"
