using BrowserApi.Generator.CSharpModel;
using BrowserApi.Generator.Emit;

namespace BrowserApi.Generator.Tests.Emit;

public class CallbackEmitterTests {
    [Fact]
    public void Emits_delegate() {
        var del = new CSharpDelegate {
            Name = "BlobCallback",
            Namespace = "BrowserApi.Dom",
            ReturnType = "void",
            Parameters = [
                new CSharpParameter { Name = "blob", CSharpType = "Blob?" }
            ]
        };

        var output = CallbackEmitter.Emit(del);

        Assert.Contains("// <auto-generated/>", output);
        Assert.Contains("namespace BrowserApi.Dom", output);
        Assert.Contains("public delegate void BlobCallback(Blob? blob);", output);
    }

    [Fact]
    public void Emits_delegate_with_multiple_params() {
        var del = new CSharpDelegate {
            Name = "EventHandler",
            Namespace = "BrowserApi.Events",
            ReturnType = "void",
            Parameters = [
                new CSharpParameter { Name = "@event", CSharpType = "Event" }
            ]
        };

        var output = CallbackEmitter.Emit(del);
        Assert.Contains("public delegate void EventHandler(Event @event);", output);
    }
}
