using BrowserApi.Generator.CSharpModel;
using BrowserApi.Generator.Emit;

namespace BrowserApi.Generator.Tests.Emit;

public class ClassEmitterTests {
    [Fact]
    public void Emits_class_with_property() {
        var csClass = new CSharpClass {
            Name = "Request",
            Namespace = "BrowserApi.Fetch",
            Properties = [
                new CSharpProperty { Name = "Method", CSharpType = "string", IsReadOnly = true, JsName = "method" }
            ]
        };

        var output = ClassEmitter.Emit(csClass);

        Assert.Contains("// <auto-generated/>", output);
        Assert.Contains("namespace BrowserApi.Fetch", output);
        Assert.Contains("public partial class Request", output);
        Assert.Contains("[JsName(\"method\")]", output);
        Assert.Contains("public string Method { get; }", output);
    }

    [Fact]
    public void Emits_class_with_base_class() {
        var csClass = new CSharpClass {
            Name = "HtmlElement",
            Namespace = "BrowserApi.Dom",
            BaseClass = "Element",
            JsName = "HTMLElement"
        };

        var output = ClassEmitter.Emit(csClass);

        Assert.Contains("[JsName(\"HTMLElement\")]", output);
        Assert.Contains("public partial class HtmlElement : Element", output);
    }

    [Fact]
    public void Emits_method() {
        var csClass = new CSharpClass {
            Name = "Console",
            Namespace = "BrowserApi.Console",
            Methods = [
                new CSharpMethod {
                    Name = "Log",
                    ReturnType = "void",
                    JsName = "log",
                    Parameters = [
                        new CSharpParameter { Name = "data", CSharpType = "params object[]", IsParams = true }
                    ]
                }
            ]
        };

        var output = ClassEmitter.Emit(csClass);

        Assert.Contains("[JsName(\"log\")]", output);
        Assert.Contains("public void Log(params object[] data) => throw new NotImplementedException();", output);
    }

    [Fact]
    public void Emits_async_method() {
        var csClass = new CSharpClass {
            Name = "Body",
            Namespace = "BrowserApi.Fetch",
            Methods = [
                new CSharpMethod {
                    Name = "TextAsync",
                    ReturnType = "Task<string>",
                    IsAsync = true
                }
            ]
        };

        var output = ClassEmitter.Emit(csClass);

        Assert.Contains("public Task<string> TextAsync() => throw new NotImplementedException();", output);
    }

    [Fact]
    public void Emits_static_property() {
        var csClass = new CSharpClass {
            Name = "Foo",
            Namespace = "BrowserApi",
            Properties = [
                new CSharpProperty { Name = "Count", CSharpType = "uint", IsStatic = true }
            ]
        };

        var output = ClassEmitter.Emit(csClass);
        Assert.Contains("public static uint Count { get; set; }", output);
    }

    [Fact]
    public void Skips_constructors_in_generated_output() {
        var csClass = new CSharpClass {
            Name = "Request",
            Namespace = "BrowserApi.Fetch",
            Constructors = [
                new CSharpConstructor {
                    Parameters = [
                        new CSharpParameter { Name = "input", CSharpType = "RequestInfo" },
                        new CSharpParameter { Name = "init", CSharpType = "RequestInit?", IsOptional = true, DefaultValue = "null" }
                    ]
                }
            ]
        };

        var output = ClassEmitter.Emit(csClass);
        // Constructors are not emitted in generated code — they'll be added by the interop layer
        Assert.DoesNotContain("public Request(", output);
    }

    [Fact]
    public void Emits_read_write_property() {
        var csClass = new CSharpClass {
            Name = "Element",
            Namespace = "BrowserApi.Dom",
            Properties = [
                new CSharpProperty { Name = "ClassName", CSharpType = "string", IsReadOnly = false }
            ]
        };

        var output = ClassEmitter.Emit(csClass);
        Assert.Contains("public string ClassName { get; set; }", output);
    }
}
