using BrowserApi.Generator.CSharpModel;
using BrowserApi.Generator.Emit;

namespace BrowserApi.Generator.Tests.Emit;

public class ClassEmitterTests {
    [Fact]
    public void Emits_class_with_readonly_property_delegation() {
        var csClass = new CSharpClass {
            Name = "Request",
            Namespace = "BrowserApi.Fetch",
            Properties = [
                new CSharpProperty { Name = "Method", CSharpType = "string", IsReadOnly = true, JsName = "method" }
            ]
        };

        var output = ClassEmitter.Emit(csClass);

        Assert.Contains("// <auto-generated/>", output);
        Assert.Contains("namespace BrowserApi.Fetch", output);
        Assert.Contains("public partial class Request", output);
        Assert.Contains("[JsName(\"method\")]", output);
        Assert.Contains("public string Method => GetProperty<string>(\"method\");", output);
    }

    [Fact]
    public void Emits_class_with_base_class() {
        var csClass = new CSharpClass {
            Name = "HtmlElement",
            Namespace = "BrowserApi.Dom",
            BaseClass = "Element",
            JsName = "HTMLElement"
        };

        var output = ClassEmitter.Emit(csClass);

        Assert.Contains("[JsName(\"HTMLElement\")]", output);
        Assert.Contains("public partial class HtmlElement : Element", output);
    }

    [Fact]
    public void Emits_void_method_with_InvokeVoid() {
        var csClass = new CSharpClass {
            Name = "Node",
            Namespace = "BrowserApi.Dom",
            Methods = [
                new CSharpMethod {
                    Name = "Normalize",
                    ReturnType = "void",
                    JsName = "normalize"
                }
            ]
        };

        var output = ClassEmitter.Emit(csClass);

        Assert.Contains("[JsName(\"normalize\")]", output);
        Assert.Contains("public void Normalize() => InvokeVoid(\"normalize\");", output);
    }

    [Fact]
    public void Emits_value_returning_method_with_Invoke() {
        var csClass = new CSharpClass {
            Name = "Node",
            Namespace = "BrowserApi.Dom",
            Methods = [
                new CSharpMethod {
                    Name = "AppendChild",
                    ReturnType = "Node",
                    JsName = "appendChild",
                    Parameters = [
                        new CSharpParameter { Name = "node", CSharpType = "Node" }
                    ]
                }
            ]
        };

        var output = ClassEmitter.Emit(csClass);

        Assert.Contains("public Node AppendChild(Node node) => Invoke<Node>(\"appendChild\", node);", output);
    }

    [Fact]
    public void Emits_async_void_method_with_InvokeVoidAsync() {
        var csClass = new CSharpClass {
            Name = "Element",
            Namespace = "BrowserApi.Dom",
            Methods = [
                new CSharpMethod {
                    Name = "ScrollIntoViewAsync",
                    ReturnType = "Task",
                    IsAsync = true,
                    JsName = "scrollIntoView",
                    Parameters = [
                        new CSharpParameter { Name = "arg", CSharpType = "object?", IsOptional = true, DefaultValue = "null" }
                    ]
                }
            ]
        };

        var output = ClassEmitter.Emit(csClass);

        Assert.Contains("public Task ScrollIntoViewAsync(object? arg = null) => InvokeVoidAsync(\"scrollIntoView\", arg);", output);
    }

    [Fact]
    public void Emits_async_returning_method_with_InvokeAsync() {
        var csClass = new CSharpClass {
            Name = "Body",
            Namespace = "BrowserApi.Fetch",
            Methods = [
                new CSharpMethod {
                    Name = "TextAsync",
                    ReturnType = "Task<string>",
                    IsAsync = true,
                    JsName = "text"
                }
            ]
        };

        var output = ClassEmitter.Emit(csClass);

        Assert.Contains("public Task<string> TextAsync() => InvokeAsync<string>(\"text\");", output);
    }

    [Fact]
    public void Emits_static_property_as_auto_property() {
        var csClass = new CSharpClass {
            Name = "Foo",
            Namespace = "BrowserApi",
            Properties = [
                new CSharpProperty { Name = "Count", CSharpType = "uint", IsStatic = true }
            ]
        };

        var output = ClassEmitter.Emit(csClass);
        Assert.Contains("public static uint Count { get; set; }", output);
    }

    [Fact]
    public void Emits_static_method_as_stub() {
        var csClass = new CSharpClass {
            Name = "Foo",
            Namespace = "BrowserApi",
            Methods = [
                new CSharpMethod { Name = "Create", ReturnType = "Foo", IsStatic = true, JsName = "create" }
            ]
        };

        var output = ClassEmitter.Emit(csClass);
        Assert.Contains("public static Foo Create() => throw new NotImplementedException();", output);
    }

    [Fact]
    public void Skips_constructors_in_generated_output() {
        var csClass = new CSharpClass {
            Name = "Request",
            Namespace = "BrowserApi.Fetch",
            Constructors = [
                new CSharpConstructor {
                    Parameters = [
                        new CSharpParameter { Name = "input", CSharpType = "RequestInfo" },
                        new CSharpParameter { Name = "init", CSharpType = "RequestInit?", IsOptional = true, DefaultValue = "null" }
                    ]
                }
            ]
        };

        var output = ClassEmitter.Emit(csClass);
        Assert.DoesNotContain("public Request(", output);
    }

    [Fact]
    public void Emits_read_write_property_with_delegation() {
        var csClass = new CSharpClass {
            Name = "Element",
            Namespace = "BrowserApi.Dom",
            Properties = [
                new CSharpProperty { Name = "ClassName", CSharpType = "string", IsReadOnly = false, JsName = "className" }
            ]
        };

        var output = ClassEmitter.Emit(csClass);
        Assert.Contains("get => GetProperty<string>(\"className\");", output);
        Assert.Contains("set => SetProperty(\"className\", value);", output);
    }

    [Fact]
    public void Emits_method_with_params_array() {
        var csClass = new CSharpClass {
            Name = "Console",
            Namespace = "BrowserApi.Console",
            Methods = [
                new CSharpMethod {
                    Name = "Log",
                    ReturnType = "void",
                    JsName = "log",
                    Parameters = [
                        new CSharpParameter { Name = "data", CSharpType = "params object[]", IsParams = true }
                    ]
                }
            ]
        };

        var output = ClassEmitter.Emit(csClass);
        Assert.Contains("public void Log(params object[] data) => InvokeVoid(\"log\", data);", output);
    }
}
