using BrowserApi.Generator.CSharpModel;
using BrowserApi.Generator.Emit;

namespace BrowserApi.Generator.Tests.Emit;

public class DictionaryEmitterTests {
    [Fact]
    public void Emits_record_class_with_optional_fields() {
        var rec = new CSharpRecordClass {
            Name = "RequestInit",
            Namespace = "BrowserApi.Fetch",
            Properties = [
                new CSharpRecordProperty { Name = "Method", CSharpType = "string?", JsName = "method" },
                new CSharpRecordProperty { Name = "Headers", CSharpType = "HeadersInit?", JsName = "headers" }
            ]
        };

        var output = DictionaryEmitter.Emit(rec);

        Assert.Contains("// <auto-generated/>", output);
        Assert.Contains("public partial record class RequestInit", output);
        Assert.Contains("[JsName(\"method\")]", output);
        Assert.Contains("public string? Method { get; init; }", output);
        Assert.Contains("public HeadersInit? Headers { get; init; }", output);
    }

    [Fact]
    public void Emits_required_field() {
        var rec = new CSharpRecordClass {
            Name = "Opts",
            Namespace = "BrowserApi",
            Properties = [
                new CSharpRecordProperty { Name = "Name", CSharpType = "string", IsRequired = true }
            ]
        };

        var output = DictionaryEmitter.Emit(rec);
        Assert.Contains("public required string Name { get; init; }", output);
    }

    [Fact]
    public void Emits_inheritance() {
        var rec = new CSharpRecordClass {
            Name = "ChildInit",
            Namespace = "BrowserApi",
            BaseRecord = "ParentInit"
        };

        var output = DictionaryEmitter.Emit(rec);
        Assert.Contains("public partial record class ChildInit : ParentInit", output);
    }

    [Fact]
    public void Emits_nullable_optional() {
        var rec = new CSharpRecordClass {
            Name = "Opts",
            Namespace = "BrowserApi",
            Properties = [
                new CSharpRecordProperty { Name = "Body", CSharpType = "string?", IsNullable = true }
            ]
        };

        var output = DictionaryEmitter.Emit(rec);
        Assert.Contains("public string? Body { get; init; }", output);
    }
}
