using BrowserApi.Generator.CSharpModel;
using BrowserApi.Generator.Emit;

namespace BrowserApi.Generator.Tests.Emit;

public class EnumEmitterTests {
    [Fact]
    public void Emits_enum_with_string_values() {
        var csEnum = new CSharpEnum {
            Name = "RequestDestination",
            Namespace = "BrowserApi.Fetch",
            Members = [
                new CSharpEnumMember { Name = "Empty", StringValue = "" },
                new CSharpEnumMember { Name = "Audio", StringValue = "audio" },
                new CSharpEnumMember { Name = "Document", StringValue = "document" }
            ]
        };

        var output = EnumEmitter.Emit(csEnum);

        Assert.Contains("// <auto-generated/>", output);
        Assert.Contains("namespace BrowserApi.Fetch", output);
        Assert.Contains("public enum RequestDestination", output);
        Assert.Contains("[StringValue(\"\")]", output);
        Assert.Contains("Empty,", output);
        Assert.Contains("[StringValue(\"audio\")]", output);
        Assert.Contains("Audio,", output);
        Assert.Contains("[StringValue(\"document\")]", output);
        // Last member has no comma
        Assert.Contains("Document\n", output);
    }

    [Fact]
    public void Emits_enum_with_kebab_case_members() {
        var csEnum = new CSharpEnum {
            Name = "FlexDirection",
            Namespace = "BrowserApi.Css",
            Members = [
                new CSharpEnumMember { Name = "Row", StringValue = "row" },
                new CSharpEnumMember { Name = "RowReverse", StringValue = "row-reverse" },
                new CSharpEnumMember { Name = "Column", StringValue = "column" },
                new CSharpEnumMember { Name = "ColumnReverse", StringValue = "column-reverse" }
            ]
        };

        var output = EnumEmitter.Emit(csEnum);

        Assert.Contains("[StringValue(\"row-reverse\")]", output);
        Assert.Contains("RowReverse,", output);
        Assert.Contains("[StringValue(\"column-reverse\")]", output);
    }
}
