using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;

namespace BrowserApi.Css.SourceGen;

/// <summary>
/// Incremental source generator that scans the consumer project's
/// <c>wwwroot/</c> folder (via <c>AdditionalFiles</c> with
/// <c>BrowserApiAsset</c> metadata) and emits a typed
/// <c>BrowserApi.Css.Authoring.Assets</c> static class. Each file's path
/// becomes a typed accessor — <c>Assets.Css.App</c> resolves to
/// <c>"css/app.css"</c>, <c>Assets.Images.Logo</c> resolves to
/// <c>"images/logo.svg"</c>.
/// </summary>
/// <remarks>
/// <para>
/// Spec §13. Folder structure is mirrored as nested static classes;
/// PascalCase identifiers come from the file/folder names with the
/// extension stripped from leaf nodes. File names with characters that
/// can't be C# identifiers are skipped silently — those are still
/// available as raw strings.
/// </para>
/// <para>
/// Wiring (in the consuming project's csproj):
/// </para>
/// <code language="xml">
/// &lt;ItemGroup&gt;
///     &lt;AdditionalFiles Include="wwwroot/**/*.*"&gt;
///         &lt;BrowserApiAsset&gt;true&lt;/BrowserApiAsset&gt;
///         &lt;AssetRootDir&gt;wwwroot/&lt;/AssetRootDir&gt;
///     &lt;/AdditionalFiles&gt;
/// &lt;/ItemGroup&gt;
/// </code>
/// </remarks>
[Generator]
public sealed class AssetGenerator : IIncrementalGenerator {
    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var assetFiles = context.AdditionalTextsProvider
            .Combine(context.AnalyzerConfigOptionsProvider)
            .Select(static (pair, _) => Resolve(pair.Left, pair.Right))
            .Where(static x => x is not null)
            .Select(static (x, _) => x!.Value)
            .Collect();

        context.RegisterSourceOutput(assetFiles, (spc, files) => {
            if (files.IsDefaultOrEmpty) return;
            var source = Emit(files);
            spc.AddSource("Assets.g.cs", source);
        });
    }

    private static AssetFile? Resolve(AdditionalText text, AnalyzerConfigOptionsProvider opts) {
        var fileOpts = opts.GetOptions(text);
        fileOpts.TryGetValue("build_metadata.AdditionalFiles.BrowserApiAsset", out var marker);
        if (string.IsNullOrEmpty(marker) || marker == "false") return null;

        fileOpts.TryGetValue("build_metadata.AdditionalFiles.AssetRootDir", out var rootDir);
        rootDir ??= "wwwroot/";

        // Compute the relative path from the asset root.
        var path = text.Path.Replace('\\', '/');
        var rootIdx = path.IndexOf(rootDir, System.StringComparison.OrdinalIgnoreCase);
        if (rootIdx < 0) return null;
        var relativePath = path.Substring(rootIdx + rootDir.Length);
        return new AssetFile(relativePath);
    }

    private static string Emit(System.Collections.Immutable.ImmutableArray<AssetFile> files) {
        var root = new AssetTreeNode("Assets");
        foreach (var f in files.OrderBy(f => f.RelativePath)) {
            root.Add(f.RelativePath);
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by BrowserApi.Css.SourceGen — do not edit.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace BrowserApi.Css.Authoring;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Typed accessors for files under the project's <c>wwwroot/</c>.");
        sb.AppendLine("/// Generated from <c>&lt;AdditionalFiles Include=\"wwwroot/**/*.*\"&gt;</c>");
        sb.AppendLine("/// items marked with <c>&lt;BrowserApiAsset&gt;true&lt;/BrowserApiAsset&gt;</c>.");
        sb.AppendLine("/// Each accessor returns the file's path relative to <c>wwwroot/</c>.");
        sb.AppendLine("/// </summary>");
        EmitTreeNode(sb, root, indent: 0);
        return sb.ToString();
    }

    private static void EmitTreeNode(StringBuilder sb, AssetTreeNode node, int indent) {
        var pad = new string(' ', indent * 4);
        sb.Append(pad).Append("public static class ").AppendLine(node.Identifier).Append(pad).AppendLine("{");

        foreach (var leaf in node.Leaves.OrderBy(l => l.Identifier)) {
            sb.Append(pad).Append("    /// <summary>Path: <c>").Append(leaf.RelativePath).AppendLine("</c>.</summary>");
            sb.Append(pad).Append("    public static string ").Append(leaf.Identifier)
              .Append(" => \"").Append(leaf.RelativePath).AppendLine("\";");
        }
        foreach (var child in node.Children.Values.OrderBy(c => c.Identifier)) {
            sb.AppendLine();
            EmitTreeNode(sb, child, indent + 1);
        }

        sb.Append(pad).AppendLine("}");
    }

    private readonly struct AssetFile {
        public AssetFile(string relativePath) { RelativePath = relativePath; }
        public string RelativePath { get; }
    }

    private sealed class AssetTreeNode {
        public string Identifier { get; }
        public Dictionary<string, AssetTreeNode> Children { get; } = new();
        public List<AssetLeaf> Leaves { get; } = new();

        public AssetTreeNode(string identifier) { Identifier = identifier; }

        public void Add(string relativePath) {
            var segments = relativePath.Split('/');
            var node = this;
            for (int i = 0; i < segments.Length - 1; i++) {
                var dirIdent = ToIdentifier(segments[i]);
                if (string.IsNullOrEmpty(dirIdent)) return;
                if (!node.Children.TryGetValue(dirIdent, out var child)) {
                    child = new AssetTreeNode(dirIdent);
                    node.Children[dirIdent] = child;
                }
                node = child;
            }
            var leafFile = segments[segments.Length - 1];
            var leafIdent = ToIdentifier(Path.GetFileNameWithoutExtension(leafFile));
            if (string.IsNullOrEmpty(leafIdent)) return;
            node.Leaves.Add(new AssetLeaf(leafIdent, relativePath));
        }
    }

    private readonly struct AssetLeaf {
        public AssetLeaf(string identifier, string relativePath) {
            Identifier = identifier;
            RelativePath = relativePath;
        }
        public string Identifier { get; }
        public string RelativePath { get; }
    }

    private static string ToIdentifier(string name) {
        if (string.IsNullOrEmpty(name)) return "";
        var sb = new StringBuilder(name.Length);
        bool capitalizeNext = true;
        foreach (var ch in name) {
            if (char.IsLetterOrDigit(ch) || ch == '_') {
                if (sb.Length == 0 && char.IsDigit(ch)) sb.Append('_');
                sb.Append(capitalizeNext ? char.ToUpperInvariant(ch) : ch);
                capitalizeNext = false;
            } else {
                capitalizeNext = true;
            }
        }
        return sb.ToString();
    }
}
