using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;

namespace BrowserApi.Css.SourceGen;

/// <summary>
/// Incremental source generator that parses external CSS files (e.g.
/// MudBlazor's bundle), extracts class selectors and custom-property
/// definitions, and emits a typed root class with nested groups.
/// </summary>
/// <remarks>
/// <para>
/// Spec §10. The CSS parser is deliberately minimal — just <c>.class</c>
/// selectors and <c>--var:</c> declarations. It is NOT a full CSS parser
/// and will not break on unknown at-rules or media queries. Selectors are
/// extracted by regex, then grouped by dash-separated segments to produce
/// the type hierarchy.
/// </para>
/// <para>
/// Wiring (consumer's csproj):
/// </para>
/// <code language="xml">
/// &lt;ItemGroup&gt;
///     &lt;AdditionalFiles Include="$(NuGetPackageRoot)mudblazor/8.0.0/staticwebassets/MudBlazor.min.css"&gt;
///         &lt;BrowserApiExternalCss&gt;true&lt;/BrowserApiExternalCss&gt;
///         &lt;ExternalCssRoot&gt;Mud&lt;/ExternalCssRoot&gt;
///         &lt;ExternalCssPrefix&gt;mud-&lt;/ExternalCssPrefix&gt;
///     &lt;/AdditionalFiles&gt;
/// &lt;/ItemGroup&gt;
/// </code>
/// <para>
/// Result: <c>Mud.Button.Primary</c> for <c>.mud-button-primary</c>,
/// <c>Mud.Palette.Primary</c> for <c>--mud-palette-primary</c>.
/// </para>
/// </remarks>
[Generator]
public sealed class ExternalCssGenerator : IIncrementalGenerator {
    private static readonly Regex ClassSelectorRegex = new(@"\.([a-zA-Z_][\w-]*)", RegexOptions.Compiled);
    private static readonly Regex CustomPropertyRegex = new(@"(--[a-zA-Z_][\w-]*)\s*:", RegexOptions.Compiled);

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var externalCssFiles = context.AdditionalTextsProvider
            .Combine(context.AnalyzerConfigOptionsProvider)
            .Select(static (pair, _) => Resolve(pair.Left, pair.Right))
            .Where(static x => x is not null)
            .Select(static (x, _) => x!.Value)
            .Collect();

        context.RegisterSourceOutput(externalCssFiles, (spc, files) => {
            if (files.IsDefaultOrEmpty) return;
            foreach (var file in files) {
                var source = Emit(file);
                spc.AddSource($"External_{file.RootClassName}.g.cs", source);
            }
        });
    }

    private static ExternalCssFile? Resolve(AdditionalText text, AnalyzerConfigOptionsProvider opts) {
        var fileOpts = opts.GetOptions(text);
        fileOpts.TryGetValue("build_metadata.AdditionalFiles.BrowserApiExternalCss", out var marker);
        if (string.IsNullOrEmpty(marker) || marker == "false") return null;

        fileOpts.TryGetValue("build_metadata.AdditionalFiles.ExternalCssRoot", out var rootClass);
        fileOpts.TryGetValue("build_metadata.AdditionalFiles.ExternalCssPrefix", out var prefix);

        if (string.IsNullOrEmpty(rootClass)) return null;
        var content = text.GetText()?.ToString() ?? "";

        return new ExternalCssFile(rootClass!, prefix ?? "", content);
    }

    private static string Emit(ExternalCssFile file) {
        // Extract class names that start with the configured prefix.
        var classes = new HashSet<string>();
        foreach (Match m in ClassSelectorRegex.Matches(file.Content)) {
            var name = m.Groups[1].Value;
            if (string.IsNullOrEmpty(file.Prefix) || name.StartsWith(file.Prefix, System.StringComparison.Ordinal)) {
                classes.Add(name);
            }
        }
        // Custom properties: --mud-palette-primary
        var customProps = new HashSet<string>();
        foreach (Match m in CustomPropertyRegex.Matches(file.Content)) {
            var name = m.Groups[1].Value;
            // Strip "--" plus the configured prefix to match the type-tree shape.
            var bare = name.Substring(2);
            if (string.IsNullOrEmpty(file.Prefix) || bare.StartsWith(file.Prefix, System.StringComparison.Ordinal)) {
                customProps.Add(bare);
            }
        }

        // Build the type tree.
        var root = new TreeNode(file.RootClassName);
        foreach (var cls in classes.OrderBy(c => c)) {
            var stripped = string.IsNullOrEmpty(file.Prefix) ? cls : cls.Substring(file.Prefix.Length);
            root.AddClass(stripped, cls);
        }
        foreach (var prop in customProps.OrderBy(p => p)) {
            var stripped = string.IsNullOrEmpty(file.Prefix) ? prop : prop.Substring(file.Prefix.Length);
            root.AddVar(stripped, "--" + prop);
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by BrowserApi.Css.SourceGen — external CSS parser. Do not edit.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using BrowserApi.Css;");
        sb.AppendLine("using BrowserApi.Css.Authoring;");
        sb.AppendLine();
        sb.AppendLine("namespace BrowserApi.Css.Authoring.External;");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>Generated bindings for an external CSS file.</summary>");
        EmitNode(sb, root, indent: 0);
        return sb.ToString();
    }

    private static void EmitNode(StringBuilder sb, TreeNode node, int indent) {
        var pad = new string(' ', indent * 4);
        sb.Append(pad).Append("public static class ").AppendLine(node.Identifier).Append(pad).AppendLine("{");

        // Avoid C# name collisions: if a leaf shares an identifier with a
        // child class, the leaf becomes a `_` accessor inside the child class
        // (Xx.Button._ for the bare ".xx-button"). The leaf is then dropped
        // from the parent so the parent's `Button` is unambiguously the class.
        var childIds = new HashSet<string>(node.Children.Keys);
        var leavesToHere = node.Classes.Where(l => !childIds.Contains(l.Identifier)).OrderBy(l => l.Identifier).ToList();
        var leavesToBumpDown = node.Classes.Where(l => childIds.Contains(l.Identifier)).ToList();
        var varsToHere = node.Vars.Where(v => !childIds.Contains(v.Identifier)).OrderBy(v => v.Identifier).ToList();

        foreach (var leaf in leavesToHere) {
            sb.Append(pad).Append("    /// <summary>External class: <c>.").Append(leaf.Original).AppendLine("</c>.</summary>");
            sb.Append(pad).Append("    public static Class ").Append(leaf.Identifier)
              .Append(" { get; } = Class.External(\"").Append(leaf.Original).AppendLine("\");");
        }
        foreach (var v in varsToHere) {
            sb.Append(pad).Append("    /// <summary>External CSS variable: <c>").Append(v.Original).AppendLine("</c>.</summary>");
            sb.Append(pad).Append("    public static CssVar<CssColor> ").Append(v.Identifier)
              .Append(" { get; } = CssVar.External<CssColor>(\"").Append(v.Original).AppendLine("\");");
        }
        foreach (var child in node.Children.Values.OrderBy(c => c.Identifier)) {
            sb.AppendLine();
            // Inject the bumped-down leaf (if any) into the child as an "_" accessor.
            var match = leavesToBumpDown.FirstOrDefault(l => l.Identifier == child.Identifier);
            if (match.Identifier is not null) {
                child.Classes.Insert(0, new Leaf("_", match.Original));
            }
            EmitNode(sb, child, indent + 1);
        }
        sb.Append(pad).AppendLine("}");
    }

    private sealed class TreeNode {
        public string Identifier { get; }
        public Dictionary<string, TreeNode> Children { get; } = new();
        public List<Leaf> Classes { get; } = new();
        public List<Leaf> Vars { get; } = new();
        public TreeNode(string identifier) { Identifier = identifier; }

        public void AddClass(string strippedName, string originalSelector) {
            var segments = strippedName.Split('-');
            Add(segments, segments.Length - 1, this, segments.Length - 1).Classes.Add(
                new Leaf(ToPascal(segments[segments.Length - 1]), originalSelector));
        }

        public void AddVar(string strippedName, string originalProperty) {
            var segments = strippedName.Split('-');
            Add(segments, segments.Length - 1, this, segments.Length - 1).Vars.Add(
                new Leaf(ToPascal(segments[segments.Length - 1]), originalProperty));
        }

        private static TreeNode Add(string[] segments, int leafIdx, TreeNode root, int totalSegs) {
            // For a 1-segment selector like ".mud-card", strip prefix already done →
            // segments=["card"]. The leaf goes directly on root.
            if (segments.Length == 1) return root;

            var node = root;
            for (int i = 0; i < segments.Length - 1; i++) {
                var dirIdent = ToPascal(segments[i]);
                if (string.IsNullOrEmpty(dirIdent)) return root;
                if (!node.Children.TryGetValue(dirIdent, out var child)) {
                    child = new TreeNode(dirIdent);
                    node.Children[dirIdent] = child;
                }
                node = child;
            }
            return node;
        }
    }

    private readonly struct Leaf {
        public Leaf(string identifier, string original) { Identifier = identifier; Original = original; }
        public string Identifier { get; }
        public string Original { get; }
    }

    private readonly struct ExternalCssFile {
        public ExternalCssFile(string rootClassName, string prefix, string content) {
            RootClassName = rootClassName;
            Prefix = prefix;
            Content = content;
        }
        public string RootClassName { get; }
        public string Prefix { get; }
        public string Content { get; }
    }

    private static string ToPascal(string name) {
        if (string.IsNullOrEmpty(name)) return "";
        var sb = new StringBuilder(name.Length);
        bool capitalizeNext = true;
        foreach (var ch in name) {
            if (char.IsLetterOrDigit(ch) || ch == '_') {
                if (sb.Length == 0 && char.IsDigit(ch)) sb.Append('_');
                sb.Append(capitalizeNext ? char.ToUpperInvariant(ch) : ch);
                capitalizeNext = false;
            } else {
                capitalizeNext = true;
            }
        }
        return sb.ToString();
    }
}
