using BrowserApi.Generator.Emit;
using BrowserApi.Generator.Transform;

namespace BrowserApi.Generator.Css;

public static class CssStyleDeclarationEmitter {
    public static string Emit(List<CssPropertyDefinition> properties) {
        var w = new CSharpCodeWriter();
        w.AppendLine("// <auto-generated/>");
        w.AppendLine("#nullable enable");
        w.AppendLine("#pragma warning disable CS8618");
        w.AppendLine();
        w.AppendLine("using BrowserApi.Common;");
        w.AppendLine();

        using (w.BeginBlock("namespace BrowserApi.Css")) {
            using (w.BeginBlock("public partial class CssStyleDeclaration")) {
                var first = true;
                foreach (var prop in properties) {
                    if (!first) w.AppendLine();
                    first = false;

                    var csType = MapPropertyToType(prop);
                    var csName = GetPropertyName(prop);
                    var jsName = GetJsPropertyName(prop);

                    if (jsName != null)
                        w.AppendLine($"[JsName(\"{jsName}\")]");

                    w.AppendLine($"public {csType} {csName} {{ get; set; }}");
                }
            }
        }

        return w.ToString();
    }

    private static string MapPropertyToType(CssPropertyDefinition prop) {
        var mappedType = CssValueTypeMapper.MapToCSharpType(prop.ValueGrammar, prop.Name);
        if (mappedType == "enum") {
            return NamingConventions.ToPascalCase(prop.Name);
        }
        return mappedType;
    }

    private static string GetPropertyName(CssPropertyDefinition prop) {
        return NamingConventions.ToPascalCase(prop.Name);
    }

    private static string? GetJsPropertyName(CssPropertyDefinition prop) {
        // Find the camelCase JS name from styleDeclaration
        foreach (var name in prop.StyleDeclarationNames) {
            if (!name.Contains('-'))
                return name;
        }
        return null;
    }
}
