using BrowserApi.Generator.Emit;

namespace BrowserApi.Generator.Css;

public static class CssValueTypeStubEmitter {
    private static readonly Dictionary<string, string> StubTypes = new() {
        ["Length"] = "0",
        ["CssColor"] = "\"\"",
        ["Duration"] = "0",
        ["Angle"] = "0",
        ["Percentage"] = "0",
        ["Resolution"] = "0",
        ["Flex"] = "0",
    };

    public static List<(string TypeName, string Code)> EmitAll() {
        var results = new List<(string, string)>();
        foreach (var (typeName, defaultVal) in StubTypes) {
            results.Add((typeName, EmitStub(typeName, defaultVal)));
        }
        return results;
    }

    private static string EmitStub(string typeName, string defaultValue) {
        var w = new CSharpCodeWriter();
        w.AppendLine("// <auto-generated/>");
        w.AppendLine("#nullable enable");
        w.AppendLine();
        w.AppendLine("using BrowserApi.Common;");
        w.AppendLine();

        using (w.BeginBlock("namespace BrowserApi.Css")) {
            using (w.BeginBlock($"public readonly partial struct {typeName} : ICssValue")) {
                w.AppendLine("private readonly string _value;");
                w.AppendLine();
                using (w.BeginBlock($"public {typeName}(string value)")) {
                    w.AppendLine("_value = value;");
                }
                w.AppendLine();
                w.AppendLine("public string ToCss() => _value;");
                w.AppendLine();
                w.AppendLine($"public override string ToString() => _value;");
            }
        }

        return w.ToString();
    }
}
