using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace BrowserApi.SourceGen;

[Generator(LanguageNames.CSharp)]
public sealed class JsModuleGenerator : IIncrementalGenerator {
    private const string AttributeFullName = "BrowserApi.SourceGen.JsModuleAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        // Step 1: Emit the JsModuleAttribute source
        context.RegisterPostInitializationOutput(static ctx => {
            ctx.AddSource("JsModuleAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8));
        });

        // Step 2: Find partial classes with [JsModule("...")]
        var classDeclarations = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, ct) => GetClassInfo(ctx, ct))
            .Where(static info => info is not null);

        // Step 3: Get all additional .js files
        var jsFiles = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith(".js"));

        // Step 4: Combine classes with JS files
        var combined = classDeclarations
            .Combine(jsFiles.Collect());

        // Step 5: Generate source
        context.RegisterSourceOutput(combined, static (spc, pair) => {
            var (classInfo, jsFiles) = pair;
            if (classInfo is null) return;
            Execute(spc, classInfo, jsFiles);
        });
    }

    private static ClassInfo? GetClassInfo(GeneratorAttributeSyntaxContext ctx, CancellationToken ct) {
        if (ctx.TargetSymbol is not INamedTypeSymbol classSymbol) return null;

        var attr = classSymbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == AttributeFullName);
        if (attr is null) return null;

        var path = attr.ConstructorArguments.FirstOrDefault().Value as string;
        if (path is null) return null;

        return new ClassInfo(
            classSymbol.Name,
            classSymbol.ContainingNamespace.IsGlobalNamespace
                ? null
                : classSymbol.ContainingNamespace.ToDisplayString(),
            path,
            GetAccessibility(classSymbol));
    }

    private static string GetAccessibility(INamedTypeSymbol symbol) {
        return symbol.DeclaredAccessibility switch {
            Accessibility.Public => "public",
            Accessibility.Internal => "internal",
            _ => "public"
        };
    }

    private static void Execute(
        SourceProductionContext context,
        ClassInfo classInfo,
        ImmutableArray<AdditionalText> jsFiles) {

        // Find matching JS file
        var jsFile = jsFiles.FirstOrDefault(f =>
            f.Path.EndsWith(classInfo.JsPath) ||
            f.Path.Replace("\\", "/").EndsWith(classInfo.JsPath.TrimStart('.', '/')));

        if (jsFile is null) {
            context.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor(
                    "BAPI001", "JS file not found",
                    "Could not find AdditionalFile matching '{0}'. Add <AdditionalFiles Include=\"{0}\" /> to your csproj.",
                    "BrowserApi.SourceGen", DiagnosticSeverity.Warning, true),
                Location.None, classInfo.JsPath));
            return;
        }

        var jsSource = jsFile.GetText(context.CancellationToken)?.ToString();
        if (jsSource is null) return;

        var functions = JsDocParser.Parse(jsSource);
        if (functions.Count == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.JSInterop;");
        sb.AppendLine();

        if (classInfo.Namespace is not null) {
            sb.AppendLine($"namespace {classInfo.Namespace};");
            sb.AppendLine();
        }

        // Class declaration — instance class with IJSRuntime injection
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// Typed C# wrapper for the <c>{classInfo.JsPath}</c> JavaScript module.");
        sb.AppendLine($"/// Register as a scoped service: <c>services.AddScoped&lt;{classInfo.ClassName}&gt;();</c>");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"{classInfo.Accessibility} partial class {classInfo.ClassName} : System.IAsyncDisposable {{");
        sb.AppendLine($"    private readonly IJSRuntime _js;");
        sb.AppendLine($"    private IJSObjectReference? _module;");
        sb.AppendLine();

        // Constructor
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Initializes a new instance of <see cref=\"{classInfo.ClassName}\"/> with the specified JS runtime.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    /// <param name=\"js\">The Blazor JS runtime, typically injected via DI.</param>");
        sb.AppendLine($"    public {classInfo.ClassName}(IJSRuntime js) => _js = js;");
        sb.AppendLine();

        // Module loader
        sb.AppendLine($"    private async System.Threading.Tasks.Task<IJSObjectReference> GetModuleAsync() {{");
        sb.AppendLine($"        return _module ??= await _js.InvokeAsync<IJSObjectReference>(\"import\", \"{classInfo.JsPath}\");");
        sb.AppendLine($"    }}");

        // Methods
        foreach (var func in functions) {
            sb.AppendLine();
            EmitFunction(sb, func);
        }

        // DisposeAsync
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>Disposes the cached JS module reference.</summary>");
        sb.AppendLine($"    public async System.Threading.Tasks.ValueTask DisposeAsync() {{");
        sb.AppendLine($"        if (_module is not null) {{");
        sb.AppendLine($"            await _module.DisposeAsync();");
        sb.AppendLine($"            _module = null;");
        sb.AppendLine($"        }}");
        sb.AppendLine($"    }}");

        sb.AppendLine("}");

        context.AddSource($"{classInfo.ClassName}.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void EmitFunction(StringBuilder sb, JsFunctionInfo func) {
        // XML doc comments
        if (func.Summary is not null) {
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// {EscapeXml(func.Summary)}");
            sb.AppendLine($"    /// </summary>");
        }

        foreach (var p in func.Params) {
            if (p.Description is not null)
                sb.AppendLine($"    /// <param name=\"{p.CSharpName}\">{EscapeXml(p.Description)}</param>");
            else
                sb.AppendLine($"    /// <param name=\"{p.CSharpName}\">The {p.Name} parameter.</param>");
        }

        if (func.ReturnsDoc is not null)
            sb.AppendLine($"    /// <returns>{EscapeXml(func.ReturnsDoc)}</returns>");

        // Method signature — no IJSRuntime parameter, it's on the instance
        var paramList = func.Params.Count > 0
            ? string.Join(", ", func.Params.Select(p => $"{p.CSharpType} {p.CSharpName}"))
            : "";

        var argList = func.Params.Count > 0
            ? ", " + string.Join(", ", func.Params.Select(p => p.CSharpName))
            : "";

        if (func.ReturnType is null || func.ReturnType == "void") {
            sb.AppendLine($"    public async System.Threading.Tasks.Task {func.CSharpName}({paramList}) {{");
            sb.AppendLine($"        var module = await GetModuleAsync();");
            sb.AppendLine($"        await module.InvokeVoidAsync(\"{func.JsName}\"{argList});");
            sb.AppendLine($"    }}");
        } else {
            var taskType = $"System.Threading.Tasks.Task<{func.ReturnType}>";
            sb.AppendLine($"    public async {taskType} {func.CSharpName}({paramList}) {{");
            sb.AppendLine($"        var module = await GetModuleAsync();");
            sb.AppendLine($"        return await module.InvokeAsync<{func.ReturnType}>(\"{func.JsName}\"{argList});");
            sb.AppendLine($"    }}");
        }
    }

    private static string EscapeXml(string text) {
        return text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
    }

    private const string AttributeSource = @"// <auto-generated/>
namespace BrowserApi.SourceGen;

/// <summary>
/// Marks a partial class as a typed wrapper for a JavaScript ES module.
/// The source generator reads the specified JS file, extracts exported function
/// signatures and JSDoc comments, and emits async C# methods that call
/// the JS functions via <c>IJSRuntime</c>.
/// </summary>
/// <remarks>
/// <para>
/// The JS file must be registered as an <c>AdditionalFile</c> in the project:
/// <code>&lt;AdditionalFiles Include=""wwwroot/js/myModule.js"" /&gt;</code>
/// </para>
/// <para>
/// The generated class receives <c>IJSRuntime</c> via constructor injection.
/// Register it as a scoped service in your DI container:
/// <code>builder.Services.AddScoped&lt;MyJsModule&gt;();</code>
/// </para>
/// <para>
/// Only <c>export function</c> declarations are processed. Default exports,
/// arrow functions, and class methods are not supported.
/// </para>
/// </remarks>
/// <example>
/// <code>
/// [JsModule(""./js/utils.js"")]
/// public partial class JsUtils;
///
/// // Program.cs:
/// builder.Services.AddScoped&lt;JsUtils&gt;();
///
/// // Component:
/// @inject JsUtils Utils
/// var result = await Utils.FormatCurrencyAsync(42.99, ""USD"");
/// </code>
/// </example>
[System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
internal sealed class JsModuleAttribute : System.Attribute {
    /// <summary>
    /// Gets the path to the JavaScript module file, relative to the web root.
    /// </summary>
    public string Path { get; }

    /// <summary>
    /// Initializes a new <see cref=""JsModuleAttribute""/> with the specified module path.
    /// </summary>
    /// <param name=""path"">
    /// The path to the JS module file (e.g., <c>""./js/utils.js""</c>).
    /// Must match an <c>AdditionalFile</c> in the project.
    /// </param>
    public JsModuleAttribute(string path) => Path = path;
}
";

    private sealed class ClassInfo {
        public string ClassName { get; }
        public string? Namespace { get; }
        public string JsPath { get; }
        public string Accessibility { get; }
        public ClassInfo(string className, string? ns, string jsPath, string accessibility) {
            ClassName = className;
            Namespace = ns;
            JsPath = jsPath;
            Accessibility = accessibility;
        }
    }
}
