using BrowserApi.Generator.CSharpModel;

namespace BrowserApi.Generator.Emit;

public static class CallbackEmitter {
    public static string Emit(CSharpDelegate del, IReadOnlySet<string>? allNamespaces = null) {
        var w = new CSharpCodeWriter();
        w.AppendLine("// <auto-generated/>");
        w.AppendLine("#nullable enable");
        w.AppendLine();
        UsingDirectives.WriteUsings(w, del.Namespace, allNamespaces);
        w.AppendLine();

        using (w.BeginBlock($"namespace {del.Namespace}")) {
            var paramList = string.Join(", ", del.Parameters.Select(p => {
                var defaultSuffix = p.DefaultValue != null ? $" = {p.DefaultValue}" : "";
                return $"{p.CSharpType} {p.Name}{defaultSuffix}";
            }));
            w.AppendLine($"public delegate {del.ReturnType} {del.Name}({paramList});");
        }

        return w.ToString();
    }
}
