using BrowserApi.Generator.CSharpModel;

namespace BrowserApi.Generator.Emit;

public static class ClassEmitter {
    public static string Emit(CSharpClass csClass, IReadOnlySet<string>? allNamespaces = null) {
        var w = new CSharpCodeWriter();
        w.AppendLine("// <auto-generated/>");
        w.AppendLine("#nullable enable");
        w.AppendLine("#pragma warning disable CS0102, CS0104, CS0108, CS0111, CS0114, CS0246, CS0542, CS0618, CS1737, CS1750, CS8600, CS8601, CS8602, CS8603, CS8604, CS8618, CS8625, CS8765");
        w.AppendLine();
        UsingDirectives.WriteUsings(w, csClass.Namespace, allNamespaces);
        w.AppendLine();

        using (w.BeginBlock($"namespace {csClass.Namespace}")) {
            var baseClause = csClass.BaseClass != null ? $" : {csClass.BaseClass}" : "";
            var jsAttr = csClass.JsName != null ? $"[JsName(\"{csClass.JsName}\")]" : null;

            if (jsAttr != null)
                w.AppendLine(jsAttr);

            using (w.BeginBlock($"public partial class {csClass.Name}{baseClause}")) {
                var first = true;

                foreach (var constant in csClass.Constants) {
                    if (!first) w.AppendLine();
                    first = false;
                    EmitConst(w, constant);
                }

                foreach (var prop in csClass.Properties) {
                    if (!first) w.AppendLine();
                    first = false;
                    EmitProperty(w, prop);
                }

                foreach (var method in csClass.Methods) {
                    if (!first) w.AppendLine();
                    first = false;
                    EmitMethod(w, method);
                }
            }
        }

        return w.ToString();
    }

    private static void EmitProperty(CSharpCodeWriter w, CSharpProperty prop) {
        if (prop.JsName != null)
            w.AppendLine($"[JsName(\"{prop.JsName}\")]");

        var staticMod = prop.IsStatic ? "static " : "";
        var jsName = prop.JsName ?? prop.Name;

        if (prop.IsStatic) {
            var accessors = prop.IsReadOnly ? "{ get; }" : "{ get; set; }";
            w.AppendLine($"public {staticMod}{prop.CSharpType} {prop.Name} {accessors}");
        } else if (prop.IsReadOnly) {
            w.AppendLine($"public {prop.CSharpType} {prop.Name} => GetProperty<{prop.CSharpType}>(\"{jsName}\");");
        } else {
            using (w.BeginBlock($"public {prop.CSharpType} {prop.Name}")) {
                w.AppendLine($"get => GetProperty<{prop.CSharpType}>(\"{jsName}\");");
                w.AppendLine($"set => SetProperty(\"{jsName}\", value);");
            }
        }
    }

    private static void EmitMethod(CSharpCodeWriter w, CSharpMethod method) {
        if (method.JsName != null)
            w.AppendLine($"[JsName(\"{method.JsName}\")]");

        var staticMod = method.IsStatic ? "static " : "";
        var paramList = FormatParameters(method.Parameters);
        var jsName = method.JsName ?? method.Name;

        if (method.IsStatic) {
            w.AppendLine($"public {staticMod}{method.ReturnType} {method.Name}({paramList}) => throw new NotImplementedException();");
            return;
        }

        var argNames = method.Parameters.Select(p => p.Name).ToList();
        var argsStr = argNames.Count > 0 ? ", " + string.Join(", ", argNames) : "";

        if (method.ReturnType == "void") {
            w.AppendLine($"public void {method.Name}({paramList}) => InvokeVoid(\"{jsName}\"{argsStr});");
        } else if (method.IsAsync && method.ReturnType == "Task") {
            w.AppendLine($"public Task {method.Name}({paramList}) => InvokeVoidAsync(\"{jsName}\"{argsStr});");
        } else if (method.IsAsync) {
            var innerType = method.ReturnType.Substring(5, method.ReturnType.Length - 6); // "Task<X>" → "X"
            w.AppendLine($"public Task<{innerType}> {method.Name}({paramList}) => InvokeAsync<{innerType}>(\"{jsName}\"{argsStr});");
        } else {
            w.AppendLine($"public {method.ReturnType} {method.Name}({paramList}) => Invoke<{method.ReturnType}>(\"{jsName}\"{argsStr});");
        }
    }

    private static void EmitConstructor(CSharpCodeWriter w, string className, CSharpConstructor ctor) {
        var paramList = FormatParameters(ctor.Parameters);
        w.AppendLine($"public {className}({paramList}) {{ }}");
    }

    private static void EmitConst(CSharpCodeWriter w, CSharpConst c) {
        w.AppendLine($"public const {c.CSharpType} {c.Name} = {c.Value};");
    }

    private static string FormatParameters(List<CSharpParameter> parameters) {
        return string.Join(", ", parameters.Select(p => {
            var defaultSuffix = p.DefaultValue != null ? $" = {p.DefaultValue}" : "";
            if (p.IsParams)
                return $"{p.CSharpType} {p.Name}";
            return $"{p.CSharpType} {p.Name}{defaultSuffix}";
        }));
    }
}
