using BrowserApi.Generator.CSharpModel;

namespace BrowserApi.Generator.Emit;

public static class DictionaryEmitter {
    public static string Emit(CSharpRecordClass rec, IReadOnlySet<string>? allNamespaces = null) {
        var w = new CSharpCodeWriter();
        w.AppendLine("// <auto-generated/>");
        w.AppendLine("#nullable enable");
        w.AppendLine("#pragma warning disable CS0104, CS0108, CS0114, CS0246, CS0618, CS1750, CS8600, CS8601, CS8602, CS8603, CS8604, CS8618, CS8625, CS8765");
        w.AppendLine();
        UsingDirectives.WriteUsings(w, rec.Namespace, allNamespaces);
        w.AppendLine();

        using (w.BeginBlock($"namespace {rec.Namespace}")) {
            var baseClause = rec.BaseRecord != null ? $" : {rec.BaseRecord}" : "";
            var jsAttr = rec.JsName != null ? $"[JsName(\"{rec.JsName}\")]" : null;

            if (jsAttr != null)
                w.AppendLine(jsAttr);

            using (w.BeginBlock($"public partial record class {rec.Name}{baseClause}")) {
                for (var i = 0; i < rec.Properties.Count; i++) {
                    if (i > 0) w.AppendLine();
                    var prop = rec.Properties[i];

                    if (prop.JsName != null)
                        w.AppendLine($"[JsName(\"{prop.JsName}\")]");

                    var requiredMod = prop.IsRequired ? "required " : "";
                    w.AppendLine($"public {requiredMod}{prop.CSharpType} {prop.Name} {{ get; init; }}");
                }
            }
        }

        return w.ToString();
    }
}
