using BrowserApi.Generator.CSharpModel;

namespace BrowserApi.Generator.Emit;

public static class EnumEmitter {
    public static string Emit(CSharpEnum csEnum) {
        var w = new CSharpCodeWriter();
        w.AppendLine("// <auto-generated/>");
        w.AppendLine();
        w.AppendLine("using BrowserApi.Common;");
        w.AppendLine();

        using (w.BeginBlock($"namespace {csEnum.Namespace}")) {
            using (w.BeginBlock($"public enum {csEnum.Name}")) {
                for (var i = 0; i < csEnum.Members.Count; i++) {
                    var member = csEnum.Members[i];
                    var comma = i < csEnum.Members.Count - 1 ? "," : "";
                    w.AppendLine($"[StringValue(\"{member.StringValue}\")]");
                    w.AppendLine($"{member.Name}{comma}");
                    if (i < csEnum.Members.Count - 1)
                        w.AppendLine();
                }
            }
        }

        return w.ToString();
    }
}
