using BrowserApi.Common;

namespace BrowserApi.Events;

/// <summary>
/// Identifies the type of pointing device that triggered a pointer event, corresponding
/// to the <c>PointerEvent.pointerType</c> property value.
/// </summary>
/// <remarks>
/// <para>
/// Each member maps to a <c>PointerEvent.pointerType</c> string value via a
/// <see cref="StringValueAttribute"/>. Use <see cref="PointerEventExtensions.GetPointerType"/>
/// to convert a <see cref="PointerEvent"/>'s raw string to this strongly-typed enum, or
/// <see cref="PointerEventExtensions.IsPointerType"/> for direct comparison.
/// </para>
/// </remarks>
/// <example>
/// <code>
/// PointerType? type = pointerEvent.GetPointerType();
/// if (type == PointerType.Touch)
/// {
///     // Handle touch-specific behavior
/// }
///
/// // Or use the extension method directly
/// if (pointerEvent.IsPointerType(PointerType.Pen))
/// {
///     // Handle pen/stylus input
/// }
/// </code>
/// </example>
/// <seealso cref="PointerEventExtensions"/>
/// <seealso cref="MouseButton"/>
public enum PointerType {
    /// <summary>The event was generated by a mouse device.</summary>
    [StringValue("mouse")] Mouse,

    /// <summary>The event was generated by a pen or stylus device.</summary>
    [StringValue("pen")] Pen,

    /// <summary>The event was generated by a touch (finger) on a touchscreen.</summary>
    [StringValue("touch")] Touch,
}
