using BrowserApi.Common;

namespace BrowserApi.Events;

/// <summary>
/// Provides extension methods for <see cref="PointerEvent"/> that add strongly-typed
/// access to the pointer device type.
/// </summary>
/// <remarks>
/// <para>
/// These extensions convert the raw <c>PointerEvent.pointerType</c> string property into the
/// strongly-typed <see cref="PointerType"/> enum. The <see cref="PointerEvent"/> class also
/// inherits all <see cref="MouseEventExtensions"/> since <c>PointerEvent</c> extends
/// <c>MouseEvent</c> in the DOM specification.
/// </para>
/// </remarks>
/// <seealso cref="PointerEvent"/>
/// <seealso cref="PointerType"/>
/// <seealso cref="MouseEventExtensions"/>
public static class PointerEventExtensions {
    /// <summary>
    /// Gets the type of pointing device that triggered this event as a strongly-typed
    /// <see cref="PointerType"/> value.
    /// </summary>
    /// <param name="e">The pointer event to inspect.</param>
    /// <returns>
    /// A <see cref="PointerType"/> value if the pointer type string matches a known device type
    /// (<c>"mouse"</c>, <c>"pen"</c>, or <c>"touch"</c>); otherwise, <see langword="null"/>
    /// for unrecognized pointer types.
    /// </returns>
    /// <example>
    /// <code>
    /// PointerType? type = pointerEvent.GetPointerType();
    /// switch (type)
    /// {
    ///     case PointerType.Mouse:
    ///         // Handle mouse input
    ///         break;
    ///     case PointerType.Touch:
    ///         // Handle touch input (e.g., larger hit targets)
    ///         break;
    ///     case PointerType.Pen:
    ///         // Handle pen/stylus input (e.g., pressure sensitivity)
    ///         break;
    ///     case null:
    ///         // Unknown pointer type
    ///         break;
    /// }
    /// </code>
    /// </example>
    public static PointerType? GetPointerType(this PointerEvent e) =>
        e.PointerType switch {
            "mouse" => Events.PointerType.Mouse,
            "pen" => Events.PointerType.Pen,
            "touch" => Events.PointerType.Touch,
            _ => null,
        };

    /// <summary>
    /// Checks whether this pointer event was generated by a specific type of pointing device.
    /// </summary>
    /// <param name="e">The pointer event to inspect.</param>
    /// <param name="type">The pointer device type to compare against.</param>
    /// <returns>
    /// <see langword="true"/> if the event's <c>pointerType</c> property matches the
    /// <see cref="StringValueAttribute"/> of the specified <see cref="PointerType"/> member;
    /// otherwise, <see langword="false"/>.
    /// </returns>
    /// <example>
    /// <code>
    /// if (pointerEvent.IsPointerType(PointerType.Touch))
    /// {
    ///     // This is a touch interaction
    /// }
    /// </code>
    /// </example>
    public static bool IsPointerType(this PointerEvent e, PointerType type) =>
        e.PointerType == type.ToStringValue();
}
