using BrowserApi.Generator.Css;

namespace BrowserApi.Generator.Tests.Css;

public class CssStyleDeclarationEmitterTests {
    [Fact]
    public void Emits_keyword_property_with_enum_type() {
        var props = new List<CssPropertyDefinition> {
            new() {
                Name = "flex-direction",
                ValueGrammar = "row | row-reverse | column | column-reverse",
                StyleDeclarationNames = ["flex-direction", "flexDirection"]
            }
        };

        var output = CssStyleDeclarationEmitter.Emit(props);

        Assert.Contains("// <auto-generated/>", output);
        Assert.Contains("namespace BrowserApi.Css", output);
        Assert.Contains("public partial class CssStyleDeclaration", output);
        Assert.Contains("[JsName(\"flexDirection\")]", output);
        Assert.Contains("public FlexDirection FlexDirection { get; set; }", output);
    }

    [Fact]
    public void Emits_color_property_with_css_type() {
        var props = new List<CssPropertyDefinition> {
            new() {
                Name = "color",
                ValueGrammar = "<color>",
                StyleDeclarationNames = ["color"]
            }
        };

        var output = CssStyleDeclarationEmitter.Emit(props);
        Assert.Contains("[JsName(\"color\")]", output);
        Assert.Contains("public CssColor Color { get; set; }", output);
    }

    [Fact]
    public void Emits_complex_property_as_string() {
        var props = new List<CssPropertyDefinition> {
            new() {
                Name = "display",
                ValueGrammar = "[ <display-outside> || <display-inside> ]",
                StyleDeclarationNames = ["display"]
            }
        };

        var output = CssStyleDeclarationEmitter.Emit(props);
        Assert.Contains("public string Display { get; set; }", output);
    }

    [Fact]
    public void Emits_multiple_properties() {
        var props = new List<CssPropertyDefinition> {
            new() { Name = "color", ValueGrammar = "<color>", StyleDeclarationNames = ["color"] },
            new() { Name = "width", ValueGrammar = "<length>", StyleDeclarationNames = ["width"] }
        };

        var output = CssStyleDeclarationEmitter.Emit(props);
        Assert.Contains("public CssColor Color { get; set; }", output);
        Assert.Contains("public Length Width { get; set; }", output);
    }
}
